name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - "*"

env:
  CARGO_TERM_COLOR: always

jobs:
  Test:
    uses: ./.github/workflows/testing.yml

  build:
    needs: [Test]
    runs-on: ${{ matrix.runner }}
    defaults:
      run:
        working-directory: ./web_server
    env:
      PROJECT_NAME: Sapphillon-Front
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            extension: ""
            runner: ubuntu-latest
            cross: true
          - target: x86_64-pc-windows-msvc
            extension: ".exe"
            runner: windows-latest
            cross: false
          # - target: x86_64-apple-darwin
          #   extension: ""
          #   runner: macos-latest
          #   cross: false
          - target: aarch64-unknown-linux-gnu
            extension: ""
            runner: ubuntu-latest
            cross: true
          # - target: aarch64-pc-windows-msvc
          #   extension: ".exe"
          #   runner: windows-latest
          #   cross: false
          - target: aarch64-apple-darwin
            extension: ""
            runner: macos-latest
            cross: false
          # - target: armv7-unknown-linux-gnueabihf
          #   extension: ""
          #   runner: ubuntu-latest
          #   cross: true

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: 20
      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install Dependencies on Windows
        if: runner.os == 'Windows'
        run: |
            choco install make --yes

      - name: Install Dependencies on MacOS
        if: runner.os == 'macOS'
        run: |
            brew install make

      - name: Install cross (if needed)
        if: ${{ matrix.cross }}
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build Project on cross
        if: ${{ matrix.cross }}
        run: |
            cross build --workspace --release --target ${{ matrix.target }} --verbose
      - name: Build Project
        if: ${{ !matrix.cross }}
        run: |
          rustup target add ${{ matrix.target }}
          cargo build --workspace --release --target ${{ matrix.target }} --verbose

      - name: Rename Artifacts
        shell: bash
        run: |
          mv target/${{ matrix.target }}/release/${{ env.PROJECT_NAME }}{,-${{ github.ref_name }}-${{ matrix.target }}${{ matrix.extension }}}

      - name: Release Artifacts
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            target/${{ matrix.target }}/release/${{ env.PROJECT_NAME }}-${{ github.ref_name }}-${{ matrix.target }}${{ matrix.extension }}

